package com.dnow.entity;

// Generated 2013-8-26 13:47:59 by Hibernate Tools 3.4.0.CR1


/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer aid;
	private User user;
	private String addressName;

	public Address() {
	}

	public Address(User user, String addressName) {
		this.user = user;
		this.addressName = addressName;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAddressName() {
		return this.addressName;
	}

	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

}
