package com.dnow.entity;

// Generated 2013-8-26 13:47:59 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer bid;
	private String brand;
	private String picture;
	private Set<Product> products = new HashSet<Product>(0);

	public Brand() {
	}

	public Brand(String brand) {
		this.brand = brand;
	}

	public Brand(String brand, String picture, Set<Product> products) {
		this.brand = brand;
		this.picture = picture;
		this.products = products;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
