package com.dnow.entity;

// Generated 2013-8-26 13:47:59 by Hibernate Tools 3.4.0.CR1

/**
 * OrderItem generated by hbm2java
 */
public class OrderItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Product product;
	private OrderForm order;
	private Integer count;

	public OrderItem() {
	}

	public OrderItem(Product product, OrderForm order, Integer count) {
		this.product = product;
		this.order = order;
		this.count = count;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public OrderForm getOrder() {
		return this.order;
	}

	public void setOrder(OrderForm order) {
		this.order = order;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
