package com.dnow.entity;

// Generated 2013-8-26 13:47:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pid;
	private Brand brand;
	private Category category;
	private String pname;
	private String description;
	private float price;
	private float discount;
	private int storage;
	private Date addtime;
	private int hasDeleted;
	private String picture;
	private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Product() {
	}

	public Product(Brand brand, Category category, String pname,
			String description, float price, float discount, int storage,
			Date addtime, int hasDeleted, String picture) {
		this.brand = brand;
		this.category = category;
		this.pname = pname;
		this.description = description;
		this.price = price;
		this.discount = discount;
		this.storage = storage;
		this.addtime = addtime;
		this.hasDeleted = hasDeleted;
		this.picture = picture;
	}

	public Product(Brand brand, Category category, String pname,
			String description, float price, float discount, int storage,
			Date addtime, int hasDeleted, String picture,
			Set<OrderItem> orderItems, Set<Comment> comments) {
		this.brand = brand;
		this.category = category;
		this.pname = pname;
		this.description = description;
		this.price = price;
		this.discount = discount;
		this.storage = storage;
		this.addtime = addtime;
		this.hasDeleted = hasDeleted;
		this.picture = picture;
		this.orderItems = orderItems;
		this.comments = comments;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public float getDiscount() {
		return this.discount;
	}

	public void setDiscount(float discount) {
		this.discount = discount;
	}

	public int getStorage() {
		return this.storage;
	}

	public void setStorage(int storage) {
		this.storage = storage;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public int getHasDeleted() {
		return this.hasDeleted;
	}

	public void setHasDeleted(int hasDeleted) {
		this.hasDeleted = hasDeleted;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Set<OrderItem> getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(Set<OrderItem> orderItems) {
		this.orderItems = orderItems;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
