package com.dnow.entity;

// Generated 2013-8-26 13:47:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer uid;
	private String username;
	private String password;
	private String nickname;
	private Integer sex;
	private String introduction;
	private String email;
	private String phone;
	private String qq;
	private String job;
	private String picture;
	private Date birthday;
	private Date regdate;
	private Date lastlogintime;
	private Set<Address> addresses = new HashSet<Address>(0);
	private Set<OrderForm> orderForms = new HashSet<OrderForm>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public User() {
	}

	public User(String username, String password, String nickname,
			Date regdate, Date lastlogintime) {
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.regdate = regdate;
		this.lastlogintime = lastlogintime;
	}

	public User(String username, String password, String nickname, Integer sex,
			String introduction, String email, String phone, String qq,
			String job, String picture, Date birthday, Date regdate,
			Date lastlogintime, Set<Address> addresses, Set<OrderForm> orderForms,
			Set<Comment> comments) {
		this.username = username;
		this.password = password;
		this.nickname = nickname;
		this.sex = sex;
		this.introduction = introduction;
		this.email = email;
		this.phone = phone;
		this.qq = qq;
		this.job = job;
		this.picture = picture;
		this.birthday = birthday;
		this.regdate = regdate;
		this.lastlogintime = lastlogintime;
		this.addresses = addresses;
		this.orderForms = orderForms;
		this.comments = comments;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	public Date getLastlogintime() {
		return this.lastlogintime;
	}

	public void setLastlogintime(Date lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

	public Set<OrderForm> getOrderForms() {
		return this.orderForms;
	}

	public void setOrderForms(Set<OrderForm> orderForms) {
		this.orderForms = orderForms;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
